filebeat: 
    prospectors:
    - paths: 
        - /var/log/messages
        - "/var/log/*.log"
        - "/var/log/nginx/*.log"
output:
    logstash:
        hosts: ["logging:5043"]

logging:
    level: warning
    to_files: true
    to_syslog: false
    files:
        path: /var/log/filebeat
        name: beats.log
        keepfiles: 7
