---
- name: Create required folder (logging) if they don't exist
  file: path=/var/log/nginx/ state=directory mode=644

- name: Create required folder (files - DMC) if they don't exist
  file: path=/var/www/diarmaidmcmanus/ state=directory mode=755

- name: Create required folder (files - MO) if they don't exist
  file: path=/var/www/madcapocelot/ state=directory mode=755

- name: Create required folder (files - ESP) if they don't exist
  file: path=/var/www/espsecurityplugin/ state=directory mode=755
  
- name: Update apt repos and install nginx
  apt: update_cache=yes name=nginx

- name: Set nginx to run on boot
  service: name=nginx enabled=yes state=started

- name: Copy over sites to sites-available
  copy: src=diarmaidmcmanus-site dest=/etc/nginx/sites-available/

- name: Create symlink to sites-enabled
  file: dest=/etc/nginx/sites-enabled/diarmaidmcmanus src=/etc/nginx/sites-available/diarmaidmcmanus-site state=link
  
- name: Pause for 10 seconds to allow nginx to come up
  pause: seconds=10

- name: Test nginx is listening on localhost
  action: uri url=http://localhost:80 return_content=yes
  register: webpage

- fail: msg="es not running"
  when: "'nginx' not in webpage.content"
