---
- become: True
  become_method: sudo
  hosts: all
  tasks:
    - name: copy hosts file
      copy: src=hosts dest=/etc/hosts owner=root group=root mode=644

  vars:
    - fail2ban_maxretry: '4'
    - fail2ban_jails:
      - name: 'ssh'
        enabled: 'true'
        action: 'action_mwl'

    
  roles:
    - beats
    - debops.fail2ban
    - geerlingguy.java
