---
- name: Run all playbooks to configure my personal server.
  hosts: all
  become: True
  become_method: sudo

  # Set up the local server firewall
- include: management_server.yml

  # Set up syslog, es, kibana
- include: logging_infrastructure.yml

  # Set up base servers
- include: base_server.yml

  # Set up web servers
- include: web_servers.yml
  
