---
- hosts: all
# include everything

# set up base servers
- include: base_servers.yml
- include: upgrade_servers.yml

# set up logging server
- include: logging.yml

# set up bastion server
- include: bastion.yml

# set up staticweb server
- include: staticweb.yml

# set up the loadbalancer & ssl terminator
#- include: loadbalancer.yml

# set up the foi server
#- include: alaveteli.yml

# set up my owncloud
- include: owncloud.yml
