---
- hosts: localhost
  connection: local
  become: True

  # Generate a keypair for logstash-forwarder
  tasks:
    - command: openssl req -x509 -batch -nodes -newkey rsa:4098 -keyout /root/logstash-forwarder.key -out /root/logstash-forwarder.crt

  roles:
    - { role: tersmitten.fail2ban }
  vars:
    fail2ban_services:
      - name: remote-ssh-logins
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 6
