---
- hosts: localhost
  connection: local
  become: True

  # Generate a keypair for logstash-forwarder
  tasks:
    - command: openssl req -x509 -batch -nodes -newkey rsa:4096 -keyout logstash-forwarder.key -subj "/C=US/ST=CA/O=Acme, Inc./CN=logging" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=IP:10.10.1.249")) -out logstash-forwarder.crt
    # above based on http://security.stackexchange.com/questions/74345/provide-subjectaltname-to-openssl-directly-on-command-line

  roles:
    - { role: tersmitten.fail2ban }
  vars:
    fail2ban_services:
      - name: remote-ssh-logins
        enabled: true
        port: ssh
        filter: sshd
        logpath: /var/log/auth.log
        maxretry: 6
