---
- hosts: scheduledtasks


  tasks:
    - name: install
      git: repo=git://github.com/diarmaid-mcmanus/pythondaft.git dest=/home/vagrant/pythondaft/ version=nohaproxy

    - name: cron
      cron: name="collect daft.ie properties" job="python3 /home/vagrant/pythondaft/daft.py" minute=0 hour=12
