---
- name: Install the included GPG-KEY-elasticsearch
  apt_key: data="{{ lookup('file', '../files/GPG-KEY-elasticsearch') }}" state=present

- name: Copy kibana.list to /etc/apt/sources.list.d/
  copy: src=../files/kibana.list dest=/etc/apt/sources.list.d/ owner=root group=root mode=644

- name: Update apt repos and install kibana
  apt: update_cache=yes name=kibana

- name: Install openjdk-7-jre-headless
  apt: name=openjdk-7-jre-headless

- name: Set kibana to run on boot
  service: name=kibana enabled=yes state=started

- name: Pause for 10 seconds to allow kibana to come up
  pause: seconds=10

- name: Test kb is listening on localhost:5601
  action: uri url=http://localhost:5601 return_content=yes
  register: webpage

- fail: msg="kibana not running on port 5601 {{ webpage.content }} "
  when: "'kibana' not in webpage.content"
